src/main/java/de/samply/edc/osse/model/FormComment.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this
 * program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it with Jersey
 * (https://jersey.java.net) (or a modified version of that library), containing parts covered by
 * the terms of the General Public License, version 2.0, the licensors of this Program grant you
 * additional permission to convey the resulting work.
 */

package de.samply.edc.osse.model;

import de.samply.edc.catalog.Vocabulary;
import de.samply.edc.utils.Utils;
import de.samply.store.JSONResource;
import de.samply.store.TimestampLiteral;
import java.io.Serializable;

/** The Class FormComment. */
public class FormComment implements Serializable, Comparable<FormComment> {

  /** The Constant serialVersionUID. */
  private static final long serialVersionUID = 5585028909855450228L;

  /** The comment. */
  private String comment;

  /** The user uri. */
  private String userUri;

  /** The user. */
  private User theUser;

  /** The timestamp. */
  private long timestamp;

  /**
   * Instantiates a new form comment.
   *
   * @param comment the comment
   * @param userUri the user uri
   * @param timestamp the timestamp
   */
  public FormComment(String comment, String userUri, long timestamp) {
    this.comment = comment;
    this.userUri = userUri;
    this.timestamp = timestamp;
  }

  /**
   * Instantiates a new form comment.
   *
   * @param data the data
   */
  public FormComment(JSONResource data) {
    readJsonResource(data);
  }

  /**
   * Gets the comment.
   *
   * @return the comment
   */
  public String getComment() {
    return comment;
  }

  /**
   * Sets the comment.
   *
   * @param comment the new comment
   */
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * Gets the user real name.
   *
   * @return the user real name
   */
  public String getUserRealName(JSONResource myConfig) {

    // If a comment was added externally, there might not be a user uri. Return "system" in that
    // case.
    if (userUri == null || userUri.length() < 1) {
      return "system";
    }

    if (theUser == null) {
      theUser = new User(Utils.getDatabase(), userUri);
      theUser.load(false, false, myConfig);
    }

    return theUser.getUserRealName();
  }

  /**
   * Get the full name (first and last name) of the user who wrote the comment.
   *
   * @return The comment author's name.
   */
  public String getUserRealName() {
    return getUserRealName(Utils.getSB().getConfig());
  }

  /**
   * Gets the timestamp.
   *
   * @return the timestamp
   */
  public long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the timestamp.
   *
   * @param timestamp the new timestamp
   */
  public void setTimestamp(long timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Read json resource.
   *
   * @param data the data
   */
  public void readJsonResource(JSONResource data) {
    if (data == null) {
      return;
    }

    this.comment = data.getProperty(Vocabulary.Comment.commentText).getValue();
    this.timestamp = data.getProperty(Vocabulary.Comment.commentTimestamp).asLong();
    try {
      this.userUri = data.getProperty(Vocabulary.Comment.commentUserURI).getValue();
    } catch (NullPointerException npe) {
      this.userUri = null;
      Utils.getLogger().debug("Property not found.", npe);
    }
  }

  /**
   * To json resource.
   *
   * @return the JSON resource
   */
  public JSONResource toJsonResource() {
    JSONResource commentResource = new JSONResource();
    commentResource.addProperty(
        Vocabulary.Comment.commentTimestamp, new TimestampLiteral(timestamp));
    commentResource.addProperty(Vocabulary.Comment.commentUserURI, userUri);
    commentResource.addProperty(Vocabulary.Comment.commentText, comment);

    return commentResource;
  }

  /* (non-Javadoc)
   * @see java.lang.Comparable#compareTo(java.lang.Object)
   */
  @Override
  public int compareTo(FormComment other) {
    return Long.compare(getTimestamp(), other.getTimestamp());
  }
}

src/main/java/de/samply/edc/control/AbstractViewBean.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this
 * program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it with Jersey
 * (https://jersey.java.net) (or a modified version of that library), containing parts covered by
 * the terms of the General Public License, version 2.0, the licensors of this Program grant you
 * additional permission to convey the resulting work.
 */

package de.samply.edc.control;

import de.samply.edc.model.ContextMenuEntry;
import de.samply.edc.model.DatatableRow;
import de.samply.edc.model.DatatableRows;
import de.samply.edc.utils.Utils;
import de.samply.store.JSONResource;
import java.io.Serializable;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import javax.faces.bean.ManagedProperty;

/** Abstract class for view scoped beans. */
public abstract class AbstractViewBean implements Serializable {

  public static final String FORM_STATE_OPEN = "open";
  public static final String DATA_OBJECT = "dataObject";
  /** Field containing a list contextMenu entries for a current view. */
  protected LinkedList<ContextMenuEntry> contextMenuList = new LinkedList<>();

  /**
   * Data Object used in some forms to contain data that we yet don't know what instance of classes
   * they might be.
   */
  protected HashMap<String, Object> dataObject;
  /** The sessionBean. */
  @ManagedProperty(value = "#{sessionBean}")
  protected AbstractSessionBean sessionBean;
  /** Hashmap containing fixed values for the view/form given by the xhtml form. */
  private HashMap<String, String> formParam;
  private JSONResource config;

  /**
   * TODO: add javadoc.
   */
  public JSONResource getConfig() {
    if (config == null) {
      config = sessionBean.getConfig();
    }
    return config;
  }

  /**
   * Method to get the sessionBean always use this, never access it directly, as sessionBean may be
   * null.
   *
   * @return the session bean
   */
  protected AbstractSessionBean getSessionBean() {
    if (sessionBean == null) {
      sessionBean = Utils.getSB();
    }

    return sessionBean;
  }

  /**
   * Sets the session bean.
   *
   * @param sessionBean the new session bean
   */
  public void setSessionBean(AbstractSessionBean sessionBean) {
    this.sessionBean = sessionBean;
  }

  /** Initialization. */
  public void init() {
    dataObject = null;

    config = sessionBean.getConfig();

    // Set the locale of the form to the language we chose to play in
    Utils.changeLanguage(getSessionBean().getLanguage());

    // prepare the context menu for the current view
    makeContextMenu();
  }

  /** Method to calculate a list of context menu entries where needed. */
  public void makeContextMenu() {}

  /**
   * Gets the context menu list.
   *
   * @return the context menu list
   */
  public List<ContextMenuEntry> getContextMenuList() {
    return contextMenuList;
  }

  /**
   * Checks if the view has a context menu.
   *
   * @return the boolean
   */
  public Boolean hasContextMenu() {
    return (contextMenuList != null && !contextMenuList.isEmpty());
  }

  /**
   * Method returning the state of a form. It defaults to "open"
   *
   * @return the state of the form
   */
  public String getFormState() {
    return FORM_STATE_OPEN;
  }

  /**
   * Gets the form param.
   *
   * @return the form param
   */
  public HashMap<String, String> getFormParam() {
    if (formParam == null) {
      formParam = new HashMap<>();
    }

    return formParam;
  }

  /**
   * Gets the form param.
   *
   * @param key the key
   * @return the form param
   */
  public String getFormParam(String key) {
    if (formParam == null) {
      formParam = new HashMap<>();
    }

    return formParam.get(key);
  }

  /**
   * Sets the form param.
   *
   * @param formParam the form param
   */
  public void setFormParam(HashMap<String, String> formParam) {
    this.formParam = formParam;
  }

  /**
   * Sets the form param.
   *
   * @param key the key
   * @param value the value
   */
  public void setFormParam(String key, String value) {
    if (formParam == null) {
      formParam = new HashMap<>();
    }

    formParam.put(key, value);
  }

  /**
   * Action method: saves values of a form to "the DB" and recalculates the context menu.
   *
   * @return @
   */
  public String save() {
    makeContextMenu();
    return save(false);
  }

  /**
   * Method to save values either by import or by form saving.
   *
   * @param wasImported the was imported
   * @return the string
   */
  public String save(Boolean wasImported) {
    return null;
  }

  /**
   * Gets the dataObject container.
   *
   * @return the hashmap container
   */
  @SuppressWarnings("unchecked")
  public HashMap<String, Object> getDataObject() {
    if (dataObject == null) {
      Object temp = getSessionBean().clearTempObject(DATA_OBJECT);
      if (temp != null) {
        dataObject = (HashMap<String, Object>) temp;
      } else {
        dataObject = new HashMap<>();
      }
    }
    return dataObject;
  }

  /**
   * Action method: To add a row to a datatable.
   *
   * @param name Name of the datatable
   * @return the string
   */
  public String addAction(String name) {
    addRow(name);
    return null;
  }

  /**
   * Action method: to delete a row from a datatable.
   *
   * @param name Name of the datatable
   * @param weg Row to be removed
   * @return the string
   */
  public String deleteAction(String name, DatatableRow weg) {
    deleteRow(name, weg);
    return null;
  }

  /**
   * Method to add a row to a datatable.
   *
   * @param name the name of the datatable to add a row to
   */
  public void addRow(String name) {
    DatatableRows stl;

    if (!dataObject.containsKey(name)) {
      stl = new DatatableRows();
    } else {
      stl = (DatatableRows) dataObject.get(name);
    }

    stl.add(new DatatableRow());
    dataObject.put(name, stl);
  }

  /**
   * Method to delete a line from a datatable.
   *
   * @param name Name of the datatable
   * @param weg Line to be removed
   */
  public void deleteRow(String name, DatatableRow weg) {
    if (!dataObject.containsKey(name)) {
      return;
    }

    DatatableRows stl = (DatatableRows) dataObject.get(name);
    stl.remove(weg);

    dataObject.put(name, stl);
  }
}

src/main/webapp/components/commonFormButtons.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui">


    <p:remoteCommand name="validationFailed" update="@all" />

    <!--
    Handling of the validation e.g. remove the flag that something has changed if
    the validation was successful. If not update page to show validation message.
    -->
    <script type="text/javascript">
      function handleComplete(xhr, status, args) {
        if(!args.validationFailed) {
          sessionStorage.setItem('somethingChangedInForm','no');
          // Also reset temporary storage of hidden values after saving
          tempFormValues = [];
        } else {
          validationFailed();
        }
      }
    </script>

    <p:commandLink styleClass="btn btn-success" style="margin-right: 20px;" id="save" action="#{formviewer.save}"
                   rendered="#{formviewer.formState == 'open' and !formviewer.upgradeInProgress}" oncomplete="handleComplete(xhr, status, args)" ajax="true" update="@all">
        <i class="fa fa-check fa-fw"/> #{msg.formbutton_save}
    </p:commandLink>

    <p:commandLink styleClass="btn btn-success" style="margin-right: 20px;" id="save_upgrade" action="#{formviewer.saveUpgradedForm}"
                   rendered="#{formviewer.formState == 'open' and formviewer.upgradeInProgress}" oncomplete="handleComplete(xhr, status, args)" ajax="true" update="@all">
        <i class="fa fa-check fa-fw"/> #{ossemsg.save_upgrade_button}
    </p:commandLink>


    <h:commandLink styleClass="btn btn-danger" value="" id="cancel" immediate="true"
                   rendered="#{formviewer.formState == 'open'}"
                   update="message"
                   action="#{sessionBean.cancelPage()}">
        <i class="fa fa-undo fa-fw"/> #{msg.cancel}

        <f:param name="disableValidation" value="true"/>
    </h:commandLink>

    <h:commandLink styleClass="btn btn-warning" style="margin-left: 20px;" id="upgrade" action="#{formviewer.upgradeForm}"
                   rendered="#{formviewer.formState == 'open' and !formviewer.formLatestVersion}">
        <i class="fa fa-arrow-up fa-fw"/> #{ossemsg.upgrade_button}

        <f:param name="disableValidation" value="true"/>
    </h:commandLink>

</ui:composition>

src/main/webapp/components/dialogFormStatus.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui">


    <p:dialog header="Change Status" widgetVar="changeFormStatusDialog" appendTo="@(body)" closeOnEscape="true"
              modal="true">
        <h:form>
            <h:panelGroup layout="block" id="topFormPanel" styleClass="panel panel-default">
                <h:panelGroup layout="block" styleClass="panel-body">

                    <h:panelGroup layout="block" styleClass="row">
                        <h:panelGroup layout="block" styleClass="col-md-12">
                            #{ossemsg.formstatus_currentStatus}: #{formviewer.form.formState} <br/>
                            #{ossemsg.formstatus_statusChangeInfo} #{msg.cancel}.
                        </h:panelGroup>
                    </h:panelGroup>
                    <br/>
                    <h:panelGroup layout="block" styleClass="row">
                        <h:panelGroup layout="block" styleClass="col-md-4">
                            <h:outputLabel for="newStatus">#{ossemsg.formstatus_newStatus}:</h:outputLabel>
                        </h:panelGroup>
                        <h:panelGroup layout="block" styleClass="col-md-8">
                            <h:selectOneMenu value="#{formviewer.newStatus}" id="newStatus" name="newStatus">
                                <f:selectItems value="#{formviewer.possibleNewStatus}"/>
                            </h:selectOneMenu>
                        </h:panelGroup>
                    </h:panelGroup>
                    <br/>
                    <h:panelGroup layout="block" styleClass="row">
                        Optional comment:
                    </h:panelGroup>
                    <h:panelGroup layout="block" styleClass="row">
                        <h:inputTextarea rows="5" cols="80"
                                         value="#{formviewer.entries['statusChangeComment']}"></h:inputTextarea>
                    </h:panelGroup>
                    <p:commandButton style="margin-right: 10px" styleClass="btn btn-success" ajax="false" type="submit"
                                     value="#{ossemsg.formstatus_changeStatus}" action="#{formviewer.changeToNewStatus()}"/>
                    <p:commandButton styleClass="btn btn-danger" value="#{msg.cancel}"
                                     onclick="PF('changeFormStatusDialog').close()"/>

                </h:panelGroup>
            </h:panelGroup>
        </h:form>
    </p:dialog>

</ui:composition>

src/main/webapp/components/formHeadPanelSymbol.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      >
<body>
<ui:composition>
<h:panelGroup title="#{msg.formstate_signed}" id="formstate_signed_symbol" style="padding-left: 10px" styleClass="fa fa-lock hasTooltip" rendered="#{formviewer.formState=='validated'}" />

<h:panelGroup title="#{msg.formstate_reported}" id="formstate_reported_symbol" style="padding-left: 10px" styleClass="fa fa-envelope hasTooltip" rendered="#{formviewer.formState=='reported'}" />
</ui:composition>

</body>
</html>

src/main/webapp/components/formUpgradePanel.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:mf="http://java.sun.com/jsf/composite/mdrfaces" xmlns:f="http://java.sun.com/jsf/core">

    <h:panelGroup id="upgradePossible" layout="block" styleClass="panel panel-warning"
                  rendered="#{sessionBean.mayWriteCurrentForm() and formviewer.formState == 'open' and !formviewer.formLatestVersion}">
        <div class="panel-heading">
            <h4>#{ossemsg.formupgrade_available_title}</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <h:outputText value="#{ossemsg.formupgrade_available}" />
                </div>
            </div>
        </div>
    </h:panelGroup>
    <h:panelGroup id="mappingSuccessful" layout="block" styleClass="panel panel-success"
                  rendered="#{formviewer.upgradeRequested and formviewer.notMappedEntries.size() == 0}">
        <div class="panel-heading">
            <h4>#{ossemsg.formupgrade_success_title}</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <h:outputText value="#{ossemsg.formupgrade_all_mappped}" />
                </div>
            </div>
        </div>
    </h:panelGroup>
    <h:panelGroup id="nonMappedElements" layout="block" styleClass="panel panel-danger"
                  rendered="#{formviewer.upgradeRequested and formviewer.notMappedEntries.size() > 0}">
        <div class="panel-heading">
            <h4>#{ossemsg.formupgrade_unmapped_elements}</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <h:outputText value="#{ossemsg.formupgrade_some_unmapped}"/>
                </div>
            </div>
            <c:forEach var="notMappedKey" items="#{formviewer.getNotMappedEntries().keySet()}">
                <c:choose>
                    <c:when test="#{formviewer.notMappedEntries[notMappedKey].getClass().simpleName eq 'DatatableRows'}">
                        <div class="abschnitt ui-corner-all">
                            <mf:mdrRecordHeader mdrId="#{fn:replace(notMappedKey, '__', ':')}" />
                            <div class="unterabschnitt ui-corner-all" style="margin-top:15px;">
                                <h:dataTable var="line" value="#{formviewer.notMappedEntries[notMappedKey].rows}"
                                             styleClass="recordTable"
                                             rendered="#{formviewer.notMappedEntries[notMappedKey].rows.size() > 0}">
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value=""/>
                                        </f:facet>
                                        <h:outputText value="#{formviewer.entries[notMappedKey].rows.indexOf(line) + 1}"/>
                                    </h:column>
                                    <c:forEach var="columnName"
                                               items="#{formviewer.notMappedEntries[notMappedKey].rows.get(0).columns.keySet()}">
                                        <h:column>
                                            <f:facet name="header">
                                                <mf:mdrLabel mdrId="#{fn:replace(columnName, '__', ':')}"></mf:mdrLabel>
                                            </f:facet>
                                            <mf:mdrInput mdrId="#{fn:replace(columnName, '__', ':')}"
                                                         value="#{line.columns[columnName]}" useSortOrder="true"/>
                                        </h:column>
                                    </c:forEach>
                                </h:dataTable>
                            </div>
                        </div>
                        <!-- Alternative solution for repeatable items: Show data elements line by line -->
<!--                        <c:forEach var="repeatableInstance" items="#{formviewer.notMappedEntries[notMappedKey].rows}">-->
<!--                            <div class="abschnitt">-->
<!--                                <h5><mf:mdrLabel mdrId="#{fn:replace(notMappedKey, '__', ':')}"></mf:mdrLabel></h5>-->
<!--                                <c:forEach var="column" items="#{repeatableInstance.columns.entrySet()}">-->
<!--                                    <h:panelGroup layout="block" styleClass="row"-->
<!--                                                  rendered="#{notMappedKey.startsWith('urn')}">-->
<!--                                        <h:panelGroup layout="block" styleClass="col-xs-3">-->
<!--                                            <mf:mdrLabel mdrId="#{fn:replace(column.key, '__', ':')}"></mf:mdrLabel>-->
<!--                                        </h:panelGroup>-->
<!--                                        <h:panelGroup layout="block" styleClass="col-xs-9">-->
<!--                                            <mf:mdrInput required="false" styleClass="mdrfaces-input"-->
<!--                                                         mdrId="#{fn:replace(column.key, '__', ':')}"-->
<!--                                                         value="#{column.value}"/>-->
<!--                                        </h:panelGroup>-->
<!--                                    </h:panelGroup>-->
<!--                                </c:forEach>-->
<!--                            </div>-->
<!--                        </c:forEach>-->
                    </c:when>
                    <c:otherwise>
                        <h:panelGroup layout="block" styleClass="row" rendered="#{notMappedKey.startsWith('urn')}">
                            <h:panelGroup layout="block" styleClass="col-xs-3">
                                <mf:mdrLabel mdrId="#{fn:replace(notMappedKey, '__', ':')}"></mf:mdrLabel>
                            </h:panelGroup>
                            <h:panelGroup layout="block" styleClass="col-xs-9">
                                <mf:mdrInput required="false" styleClass="mdrfaces-input"
                                             mdrId="#{fn:replace(notMappedKey, '__', ':')}"
                                             value="#{formviewer.notMappedEntries[notMappedKey]}"/>
                            </h:panelGroup>
                        </h:panelGroup>
                    </c:otherwise>
                </c:choose>
            </c:forEach>
        </div>
        <div class="panel-footer" style="background-color: #f2dede;">&#160;</div>
    </h:panelGroup>
    <h:outputScript>
        $(function () {
            $('#nonMappedElements').find(':input').prop('disabled', true);
        })
    </h:outputScript>
</ui:composition>

src/main/webapp/components/formcomments.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui">

    <p:overlayPanel id="commentPanel" for="commentBtn" hideEffect="fade" dynamic="true" style="width:600px" appendToBody="true">
        <p:dataTable var="comment" value="#{formviewer.formComments}" rows="5" paginator="true" paginatorPosition="top">
            <p:column headerText="#{ossemsg.formcomments_timestamp}" width="20%">
                <h:outputText value="#{comment.timestamp}">
                    <f:convertDateTime pattern="yyyy-MM-dd HH:mm:ss" type="date"/>
                </h:outputText>
            </p:column>
            <p:column headerText="#{ossemsg.formcomments_who}" width="20%">
                <h:outputText value="#{comment.userRealName}"/>
            </p:column>
            <p:column headerText="#{ossemsg.formcomments_comment}" width="60%">
                <h:outputText value="#{comment.comment}"/>
            </p:column>
        </p:dataTable>

    </p:overlayPanel>

</ui:composition>

src/main/webapp/components/navbar_left.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                xmlns:h="http://java.sun.com/jsf/html">

    <h:form>
        <div class="float-left">
            <div class="col" id="logo">
                <!--<h:graphicImage width="60" height="23" alt="OSSE" name="images/osse/#{fn:toLowerCase(request.servletContext.servletContextName)}_logo_white.svg"/>-->
                <h:graphicImage width="60" height="23" alt="OSSE" name="images/osse/osse_logo_white.svg"/>
                <h:panelGroup styleClass="osseLogoSideText"
                              rendered="#{applicationBean.isBridgehead()}">Bridgehead</h:panelGroup>
            </div>
            <ui:fragment
                    rendered="#{sessionBean.currentRole.isAdminRole() or sessionBean.currentRole.isLocalAdminRole()}">
                <h:commandLink styleClass="col"
                               action="#{sessionBean.goStartPage()}" id="list_administration">Administration
                </h:commandLink>
            </ui:fragment>
            <ui:fragment
                    rendered="#{!(sessionBean.currentRole.isAdminRole() or sessionBean.currentRole.isLocalAdminRole() or sessionBean.currentRole.isPatientRole()) and sessionBean.useDashboard}">
                <h:commandLink styleClass="col"
                               action="#{sessionBean.goStartPage()}" id="start_page">#{ossemsg.dashboard_title}
                </h:commandLink>
            </ui:fragment>
            <ui:fragment
                    rendered="#{!(sessionBean.currentRole.isAdminRole() or sessionBean.currentRole.isLocalAdminRole() or sessionBean.currentRole.isPatientRole())}">
                <h:commandLink styleClass="col"
                               action="patientlist?faces-redirect=true" id="patient_list">#{ossemsg.list_of_patients}
                </h:commandLink>
            </ui:fragment>
        </div>
    </h:form>

</ui:composition>